services:
  - type: web
    name: chatapp-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromSecret: mongodb_uri
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://chatapp-frontend.vercel.app
    healthCheckPath: /health
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    autoDeploy: true
    plan: starter
